<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Pilih--BenefitCost</name>
   <tag></tag>
   <elementGuidId>af04e2ca-1483-497c-b831-36f290418acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;type&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dd052ede-b9f9-48cc-a140-f268e39ac6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>6d2e667e-af63-4f41-a6e7-72751879b1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>756a2ccc-5bd8-4f03-a663-a31c561d64a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						--Pilih--
						Benefit
						Cost						
					</value>
      <webElementGuid>61b8b186-2605-4575-bbe4-2783aedb9c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;card shadow mb-4&quot;]/form[1]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-md-6&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>193c8dcd-067e-46df-9c3d-1e1635198e80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='type']</value>
      <webElementGuid>32f64312-bd7a-4b9b-b4a1-0e9b7c5ff17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/form/div/div/div[3]/select</value>
      <webElementGuid>4475c6ec-cdca-4dee-83cc-bd06d7850919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type Kriteria'])[1]/following::select[1]</value>
      <webElementGuid>d337098b-e8ee-496d-968f-5c3ec7e01d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Kriteria'])[1]/following::select[1]</value>
      <webElementGuid>e7168302-71f4-45b6-af2a-794d0abda0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bobot Kriteria'])[1]/preceding::select[1]</value>
      <webElementGuid>daf0e9a8-ad7f-49d6-ac84-7487c10e5127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Penilaian'])[1]/preceding::select[1]</value>
      <webElementGuid>9bbce3ba-cbb1-48aa-8d9e-300e1bca99f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9053b708-2a2c-44d4-bcbc-28a670db1b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'type' and (text() = '
						--Pilih--
						Benefit
						Cost						
					' or . = '
						--Pilih--
						Benefit
						Cost						
					')]</value>
      <webElementGuid>33d8a335-1b7c-4f79-953c-fc7b9e3a265b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
