<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Data Kriteria</name>
   <tag></tag>
   <elementGuidId>2a049a9b-bad0-429a-8ecb-3a3f46645f5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-secondary.text-decoration-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div[3]/div/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d666f08-ce27-46d6-86d2-2fc821ea3dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>list-kriteria.php</value>
      <webElementGuid>8ae5c59d-3bd2-45fe-8515-425dd8131b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-secondary text-decoration-none</value>
      <webElementGuid>da060113-88a7-4831-8d4a-5714492486e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Kriteria</value>
      <webElementGuid>15cd12c5-cdf4-4751-b771-58ac5d21515a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-4 col-md-6 mb-4&quot;]/div[@class=&quot;card border-left-info shadow h-100 py-2&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row no-gutters align-items-center&quot;]/div[@class=&quot;col mr-2&quot;]/div[@class=&quot;h5 mb-0 font-weight-bold text-gray-800&quot;]/a[@class=&quot;text-secondary text-decoration-none&quot;]</value>
      <webElementGuid>6950a3d1-44ba-4850-8e1f-c44b02551ba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div[3]/div/div/div/div/div/div/a</value>
      <webElementGuid>93f2fea2-a91d-4fc6-8b95-36945fc6b86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Data Kriteria')]</value>
      <webElementGuid>c5866b95-40f2-49ae-8331-c6194a460ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin!'])[1]/following::a[1]</value>
      <webElementGuid>19c06a19-3c61-41d1-a1dc-2fdb518b9f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>f47514be-1297-4d27-8a7b-958fb988e05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Sub Kriteria'])[2]/preceding::a[1]</value>
      <webElementGuid>e3bafd8d-0ff9-47f2-9d51-1bb3d7d5c011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Siswa'])[2]/preceding::a[2]</value>
      <webElementGuid>9f17c33a-4997-4628-8366-2ad6317528ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'list-kriteria.php')])[2]</value>
      <webElementGuid>bfe55bbb-c4dc-413f-85b7-67f82a7c761f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>b4b75051-ab52-414c-9e54-7218e9bebe38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'list-kriteria.php' and (text() = 'Data Kriteria' or . = 'Data Kriteria')]</value>
      <webElementGuid>4f56d20a-1cab-4180-82e7-290389e2c552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
