<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_X_fa fa-edit</name>
   <tag></tag>
   <elementGuidId>3d1c7540-1f70-451b-8691-4c034b3dded9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dataTable']/tbody/tr/td[6]/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>86d68946-e385-45b7-9977-a4d2caa57b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit</value>
      <webElementGuid>3274a09d-8875-4afc-8cd7-01ffee5a05af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]/div[@class=&quot;btn-group&quot;]/a[@class=&quot;btn btn-warning btn-sm&quot;]/i[@class=&quot;fa fa-edit&quot;]</value>
      <webElementGuid>8dd6b55d-eb4b-48bb-8c1a-1274f856f2d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dataTable']/tbody/tr/td[6]/div/a/i</value>
      <webElementGuid>949d6d96-706e-46cf-be30-b1adc5712af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/a/i</value>
      <webElementGuid>0ae1dc53-9e84-425b-a343-08399ad28c8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
