<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_XI_btn btn-danger btn-sm</name>
   <tag></tag>
   <elementGuidId>5894577b-b63d-4c98-b3fb-fd5e063a532f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;return confirm ('Apakah anda yakin untuk meghapus data ini')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8e7dd62-ff26-4c8c-b829-26e8891602ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>d7e188a4-ff0c-4439-a96d-2f01df7077e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>2f17670a-e48f-4bf8-8c6c-b627379f0b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hapus Data</value>
      <webElementGuid>d29f263a-a1ab-4469-9157-9da5897b5500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>hapus-alternatif.php?id=102</value>
      <webElementGuid>5398f08e-8f63-4c15-89cc-1b13945b4364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm ('Apakah anda yakin untuk meghapus data ini')</value>
      <webElementGuid>65480aae-3280-4ed1-bb5b-d58b6e575224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>535ee251-2660-4592-83f9-85f442348369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]/div[@class=&quot;btn-group&quot;]/a[@class=&quot;btn btn-danger btn-sm&quot;]</value>
      <webElementGuid>e9b050d7-bbef-49f5-b90c-a1f6e0241fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;return confirm ('Apakah anda yakin untuk meghapus data ini')&quot;]</value>
      <webElementGuid>05623e14-33a6-4218-9ca8-c76cd30fc52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dataTable']/tbody/tr/td[6]/div/a[2]</value>
      <webElementGuid>cdb1c8b0-53e5-4489-b984-819a20f95a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XI'])[1]/following::a[2]</value>
      <webElementGuid>b890c8f1-8c45-4079-969f-b1b2c12a3290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen Perkantoran'])[1]/following::a[2]</value>
      <webElementGuid>fc04ed12-88cf-4c47-957e-29ba463927ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 11 to 11 of 11 entries'])[1]/preceding::a[1]</value>
      <webElementGuid>584fb6f2-3d8d-4291-8039-857571d5996f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::a[6]</value>
      <webElementGuid>3a46865f-167b-4cde-9df8-5a6ba96e81ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'hapus-alternatif.php?id=102')]</value>
      <webElementGuid>46ba90c3-5b32-4579-b388-e3fb73904fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/a[2]</value>
      <webElementGuid>3a16365e-e334-4347-8daa-0bab38d1e533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Hapus Data' and @href = 'hapus-alternatif.php?id=102']</value>
      <webElementGuid>b788c457-d6e0-42ac-a666-b5e499437672</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
